// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: kv.proto

package kvpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type OperationType int32

const (
	OperationType_STORE  OperationType = 0
	OperationType_GET    OperationType = 1
	OperationType_DELETE OperationType = 2
)

// Enum value maps for OperationType.
var (
	OperationType_name = map[int32]string{
		0: "STORE",
		1: "GET",
		2: "DELETE",
	}
	OperationType_value = map[string]int32{
		"STORE":  0,
		"GET":    1,
		"DELETE": 2,
	}
)

func (x OperationType) Enum() *OperationType {
	p := new(OperationType)
	*p = x
	return p
}

func (x OperationType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (OperationType) Descriptor() protoreflect.EnumDescriptor {
	return file_kv_proto_enumTypes[0].Descriptor()
}

func (OperationType) Type() protoreflect.EnumType {
	return &file_kv_proto_enumTypes[0]
}

func (x OperationType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use OperationType.Descriptor instead.
func (OperationType) EnumDescriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{0}
}

type ErrorType int32

const (
	ErrorType_NOT_ALIVE   ErrorType = 0
	ErrorType_NOT_LEADER  ErrorType = 1
	ErrorType_NOT_FOUND   ErrorType = 2
	ErrorType_BAD_REQUEST ErrorType = 3
	ErrorType_UNEXPECTED  ErrorType = 4
	ErrorType_TIMEOUT     ErrorType = 5
)

// Enum value maps for ErrorType.
var (
	ErrorType_name = map[int32]string{
		0: "NOT_ALIVE",
		1: "NOT_LEADER",
		2: "NOT_FOUND",
		3: "BAD_REQUEST",
		4: "UNEXPECTED",
		5: "TIMEOUT",
	}
	ErrorType_value = map[string]int32{
		"NOT_ALIVE":   0,
		"NOT_LEADER":  1,
		"NOT_FOUND":   2,
		"BAD_REQUEST": 3,
		"UNEXPECTED":  4,
		"TIMEOUT":     5,
	}
)

func (x ErrorType) Enum() *ErrorType {
	p := new(ErrorType)
	*p = x
	return p
}

func (x ErrorType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrorType) Descriptor() protoreflect.EnumDescriptor {
	return file_kv_proto_enumTypes[1].Descriptor()
}

func (ErrorType) Type() protoreflect.EnumType {
	return &file_kv_proto_enumTypes[1]
}

func (x ErrorType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrorType.Descriptor instead.
func (ErrorType) EnumDescriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{1}
}

type KVRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Op            OperationType          `protobuf:"varint,1,opt,name=op,proto3,enum=kvpb.OperationType" json:"op,omitempty"`
	Bucket        string                 `protobuf:"bytes,2,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *KVRequest) Reset() {
	*x = KVRequest{}
	mi := &file_kv_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KVRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KVRequest) ProtoMessage() {}

func (x *KVRequest) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KVRequest.ProtoReflect.Descriptor instead.
func (*KVRequest) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{0}
}

func (x *KVRequest) GetOp() OperationType {
	if x != nil {
		return x.Op
	}
	return OperationType_STORE
}

func (x *KVRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *KVRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *KVRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type ClientResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Error         ErrorType              `protobuf:"varint,2,opt,name=error,proto3,enum=kvpb.ErrorType" json:"error,omitempty"`
	Value         string                 `protobuf:"bytes,3,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClientResponse) Reset() {
	*x = ClientResponse{}
	mi := &file_kv_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClientResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientResponse) ProtoMessage() {}

func (x *ClientResponse) ProtoReflect() protoreflect.Message {
	mi := &file_kv_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientResponse.ProtoReflect.Descriptor instead.
func (*ClientResponse) Descriptor() ([]byte, []int) {
	return file_kv_proto_rawDescGZIP(), []int{1}
}

func (x *ClientResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ClientResponse) GetError() ErrorType {
	if x != nil {
		return x.Error
	}
	return ErrorType_NOT_ALIVE
}

func (x *ClientResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

var File_kv_proto protoreflect.FileDescriptor

const file_kv_proto_rawDesc = "" +
	"\n" +
	"\bkv.proto\x12\x04kvpb\"p\n" +
	"\tKVRequest\x12#\n" +
	"\x02op\x18\x01 \x01(\x0e2\x13.kvpb.OperationTypeR\x02op\x12\x16\n" +
	"\x06bucket\x18\x02 \x01(\tR\x06bucket\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\"g\n" +
	"\x0eClientResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12%\n" +
	"\x05error\x18\x02 \x01(\x0e2\x0f.kvpb.ErrorTypeR\x05error\x12\x14\n" +
	"\x05value\x18\x03 \x01(\tR\x05value*/\n" +
	"\rOperationType\x12\t\n" +
	"\x05STORE\x10\x00\x12\a\n" +
	"\x03GET\x10\x01\x12\n" +
	"\n" +
	"\x06DELETE\x10\x02*g\n" +
	"\tErrorType\x12\r\n" +
	"\tNOT_ALIVE\x10\x00\x12\x0e\n" +
	"\n" +
	"NOT_LEADER\x10\x01\x12\r\n" +
	"\tNOT_FOUND\x10\x02\x12\x0f\n" +
	"\vBAD_REQUEST\x10\x03\x12\x0e\n" +
	"\n" +
	"UNEXPECTED\x10\x04\x12\v\n" +
	"\aTIMEOUT\x10\x052D\n" +
	"\aKVStore\x129\n" +
	"\x10PerformOperation\x12\x0f.kvpb.KVRequest\x1a\x14.kvpb.ClientResponseB\x10Z\x0egrpc/kvpb;kvpbb\x06proto3"

var (
	file_kv_proto_rawDescOnce sync.Once
	file_kv_proto_rawDescData []byte
)

func file_kv_proto_rawDescGZIP() []byte {
	file_kv_proto_rawDescOnce.Do(func() {
		file_kv_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_kv_proto_rawDesc), len(file_kv_proto_rawDesc)))
	})
	return file_kv_proto_rawDescData
}

var file_kv_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_kv_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_kv_proto_goTypes = []any{
	(OperationType)(0),     // 0: kvpb.OperationType
	(ErrorType)(0),         // 1: kvpb.ErrorType
	(*KVRequest)(nil),      // 2: kvpb.KVRequest
	(*ClientResponse)(nil), // 3: kvpb.ClientResponse
}
var file_kv_proto_depIdxs = []int32{
	0, // 0: kvpb.KVRequest.op:type_name -> kvpb.OperationType
	1, // 1: kvpb.ClientResponse.error:type_name -> kvpb.ErrorType
	2, // 2: kvpb.KVStore.PerformOperation:input_type -> kvpb.KVRequest
	3, // 3: kvpb.KVStore.PerformOperation:output_type -> kvpb.ClientResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_kv_proto_init() }
func file_kv_proto_init() {
	if File_kv_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_kv_proto_rawDesc), len(file_kv_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_kv_proto_goTypes,
		DependencyIndexes: file_kv_proto_depIdxs,
		EnumInfos:         file_kv_proto_enumTypes,
		MessageInfos:      file_kv_proto_msgTypes,
	}.Build()
	File_kv_proto = out.File
	file_kv_proto_goTypes = nil
	file_kv_proto_depIdxs = nil
}
