// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v5.29.3
// source: orca.proto

package orcapb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogType int32

const (
	LogType_OPERATION LogType = 0
	LogType_FAILURE   LogType = 1
	LogType_RECOVERY  LogType = 2
)

// Enum value maps for LogType.
var (
	LogType_name = map[int32]string{
		0: "OPERATION",
		1: "FAILURE",
		2: "RECOVERY",
	}
	LogType_value = map[string]int32{
		"OPERATION": 0,
		"FAILURE":   1,
		"RECOVERY":  2,
	}
)

func (x LogType) Enum() *LogType {
	p := new(LogType)
	*p = x
	return p
}

func (x LogType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogType) Descriptor() protoreflect.EnumDescriptor {
	return file_orca_proto_enumTypes[0].Descriptor()
}

func (LogType) Type() protoreflect.EnumType {
	return &file_orca_proto_enumTypes[0]
}

func (x LogType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogType.Descriptor instead.
func (LogType) EnumDescriptor() ([]byte, []int) {
	return file_orca_proto_rawDescGZIP(), []int{0}
}

type FailureType int32

const (
	FailureType_REVIVE  FailureType = 0
	FailureType_RANDOM  FailureType = 1
	FailureType_LEADER  FailureType = 2
	FailureType_REPLICA FailureType = 3
)

// Enum value maps for FailureType.
var (
	FailureType_name = map[int32]string{
		0: "REVIVE",
		1: "RANDOM",
		2: "LEADER",
		3: "REPLICA",
	}
	FailureType_value = map[string]int32{
		"REVIVE":  0,
		"RANDOM":  1,
		"LEADER":  2,
		"REPLICA": 3,
	}
)

func (x FailureType) Enum() *FailureType {
	p := new(FailureType)
	*p = x
	return p
}

func (x FailureType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (FailureType) Descriptor() protoreflect.EnumDescriptor {
	return file_orca_proto_enumTypes[1].Descriptor()
}

func (FailureType) Type() protoreflect.EnumType {
	return &file_orca_proto_enumTypes[1]
}

func (x FailureType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use FailureType.Descriptor instead.
func (FailureType) EnumDescriptor() ([]byte, []int) {
	return file_orca_proto_rawDescGZIP(), []int{1}
}

type LogEntry struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	LogType LogType                `protobuf:"varint,1,opt,name=logType,proto3,enum=orca.LogType" json:"logType,omitempty"`
	Term    int64                  `protobuf:"varint,2,opt,name=term,proto3" json:"term,omitempty"`
	// payload is only needed when logType is OPERATION; FAILURE/RECOVERY entries
	// can leave it empty.
	Payload []byte `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	// nodeId is required when the log represents a FAILURE or RECOVERY so
	// the system knows which node to affect.
	NodeId        string `protobuf:"bytes,4,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_orca_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_orca_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_orca_proto_rawDescGZIP(), []int{0}
}

func (x *LogEntry) GetLogType() LogType {
	if x != nil {
		return x.LogType
	}
	return LogType_OPERATION
}

func (x *LogEntry) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *LogEntry) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *LogEntry) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

type AppendEntriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int64                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	LeaderId      string                 `protobuf:"bytes,2,opt,name=leaderId,proto3" json:"leaderId,omitempty"`
	PrevLogIndex  int64                  `protobuf:"varint,3,opt,name=prevLogIndex,proto3" json:"prevLogIndex,omitempty"`
	PrevLogTerm   int64                  `protobuf:"varint,4,opt,name=prevLogTerm,proto3" json:"prevLogTerm,omitempty"`
	Entries       []*LogEntry            `protobuf:"bytes,5,rep,name=entries,proto3" json:"entries,omitempty"`
	LeaderCommit  int64                  `protobuf:"varint,6,opt,name=leaderCommit,proto3" json:"leaderCommit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendEntriesRequest) Reset() {
	*x = AppendEntriesRequest{}
	mi := &file_orca_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEntriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEntriesRequest) ProtoMessage() {}

func (x *AppendEntriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orca_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEntriesRequest.ProtoReflect.Descriptor instead.
func (*AppendEntriesRequest) Descriptor() ([]byte, []int) {
	return file_orca_proto_rawDescGZIP(), []int{1}
}

func (x *AppendEntriesRequest) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *AppendEntriesRequest) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

func (x *AppendEntriesRequest) GetPrevLogIndex() int64 {
	if x != nil {
		return x.PrevLogIndex
	}
	return 0
}

func (x *AppendEntriesRequest) GetPrevLogTerm() int64 {
	if x != nil {
		return x.PrevLogTerm
	}
	return 0
}

func (x *AppendEntriesRequest) GetEntries() []*LogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *AppendEntriesRequest) GetLeaderCommit() int64 {
	if x != nil {
		return x.LeaderCommit
	}
	return 0
}

type AppendEntriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int64                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendEntriesResponse) Reset() {
	*x = AppendEntriesResponse{}
	mi := &file_orca_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEntriesResponse) ProtoMessage() {}

func (x *AppendEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orca_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEntriesResponse.ProtoReflect.Descriptor instead.
func (*AppendEntriesResponse) Descriptor() ([]byte, []int) {
	return file_orca_proto_rawDescGZIP(), []int{2}
}

func (x *AppendEntriesResponse) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *AppendEntriesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *AppendEntriesResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type RequestVoteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int64                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	CandidateId   string                 `protobuf:"bytes,2,opt,name=candidateId,proto3" json:"candidateId,omitempty"`
	LastLogIndex  int64                  `protobuf:"varint,3,opt,name=lastLogIndex,proto3" json:"lastLogIndex,omitempty"`
	LastLogTerm   int64                  `protobuf:"varint,4,opt,name=lastLogTerm,proto3" json:"lastLogTerm,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestVoteRequest) Reset() {
	*x = RequestVoteRequest{}
	mi := &file_orca_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestVoteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVoteRequest) ProtoMessage() {}

func (x *RequestVoteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orca_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVoteRequest.ProtoReflect.Descriptor instead.
func (*RequestVoteRequest) Descriptor() ([]byte, []int) {
	return file_orca_proto_rawDescGZIP(), []int{3}
}

func (x *RequestVoteRequest) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RequestVoteRequest) GetCandidateId() string {
	if x != nil {
		return x.CandidateId
	}
	return ""
}

func (x *RequestVoteRequest) GetLastLogIndex() int64 {
	if x != nil {
		return x.LastLogIndex
	}
	return 0
}

func (x *RequestVoteRequest) GetLastLogTerm() int64 {
	if x != nil {
		return x.LastLogTerm
	}
	return 0
}

type RequestVoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int64                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	VoteGranted   bool                   `protobuf:"varint,2,opt,name=voteGranted,proto3" json:"voteGranted,omitempty"`
	Error         string                 `protobuf:"bytes,3,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestVoteResponse) Reset() {
	*x = RequestVoteResponse{}
	mi := &file_orca_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestVoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVoteResponse) ProtoMessage() {}

func (x *RequestVoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_orca_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVoteResponse.ProtoReflect.Descriptor instead.
func (*RequestVoteResponse) Descriptor() ([]byte, []int) {
	return file_orca_proto_rawDescGZIP(), []int{4}
}

func (x *RequestVoteResponse) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RequestVoteResponse) GetVoteGranted() bool {
	if x != nil {
		return x.VoteGranted
	}
	return false
}

func (x *RequestVoteResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

type StoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	Bucket        string                 `protobuf:"bytes,3,opt,name=bucket,proto3" json:"bucket,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StoreRequest) Reset() {
	*x = StoreRequest{}
	mi := &file_orca_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StoreRequest) ProtoMessage() {}

func (x *StoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orca_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StoreRequest.ProtoReflect.Descriptor instead.
func (*StoreRequest) Descriptor() ([]byte, []int) {
	return file_orca_proto_rawDescGZIP(), []int{5}
}

func (x *StoreRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *StoreRequest) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *StoreRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

type GetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Bucket        string                 `protobuf:"bytes,2,opt,name=bucket,proto3" json:"bucket,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRequest) Reset() {
	*x = GetRequest{}
	mi := &file_orca_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRequest) ProtoMessage() {}

func (x *GetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orca_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRequest.ProtoReflect.Descriptor instead.
func (*GetRequest) Descriptor() ([]byte, []int) {
	return file_orca_proto_rawDescGZIP(), []int{6}
}

func (x *GetRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *GetRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

type DeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Bucket        string                 `protobuf:"bytes,2,opt,name=bucket,proto3" json:"bucket,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteRequest) Reset() {
	*x = DeleteRequest{}
	mi := &file_orca_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteRequest) ProtoMessage() {}

func (x *DeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orca_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteRequest.ProtoReflect.Descriptor instead.
func (*DeleteRequest) Descriptor() ([]byte, []int) {
	return file_orca_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *DeleteRequest) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

type CauseFailureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          FailureType            `protobuf:"varint,1,opt,name=type,proto3,enum=orca.FailureType" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CauseFailureRequest) Reset() {
	*x = CauseFailureRequest{}
	mi := &file_orca_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CauseFailureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CauseFailureRequest) ProtoMessage() {}

func (x *CauseFailureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_orca_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CauseFailureRequest.ProtoReflect.Descriptor instead.
func (*CauseFailureRequest) Descriptor() ([]byte, []int) {
	return file_orca_proto_rawDescGZIP(), []int{8}
}

func (x *CauseFailureRequest) GetType() FailureType {
	if x != nil {
		return x.Type
	}
	return FailureType_REVIVE
}

var File_orca_proto protoreflect.FileDescriptor

const file_orca_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"orca.proto\x12\x04orca\x1a\x1bgoogle/protobuf/empty.proto\x1a\x1egoogle/protobuf/wrappers.proto\"y\n" +
	"\bLogEntry\x12'\n" +
	"\alogType\x18\x01 \x01(\x0e2\r.orca.LogTypeR\alogType\x12\x12\n" +
	"\x04term\x18\x02 \x01(\x03R\x04term\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x16\n" +
	"\x06nodeId\x18\x04 \x01(\tR\x06nodeId\"\xda\x01\n" +
	"\x14AppendEntriesRequest\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x03R\x04term\x12\x1a\n" +
	"\bleaderId\x18\x02 \x01(\tR\bleaderId\x12\"\n" +
	"\fprevLogIndex\x18\x03 \x01(\x03R\fprevLogIndex\x12 \n" +
	"\vprevLogTerm\x18\x04 \x01(\x03R\vprevLogTerm\x12(\n" +
	"\aentries\x18\x05 \x03(\v2\x0e.orca.LogEntryR\aentries\x12\"\n" +
	"\fleaderCommit\x18\x06 \x01(\x03R\fleaderCommit\"[\n" +
	"\x15AppendEntriesResponse\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x03R\x04term\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"\x90\x01\n" +
	"\x12RequestVoteRequest\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x03R\x04term\x12 \n" +
	"\vcandidateId\x18\x02 \x01(\tR\vcandidateId\x12\"\n" +
	"\flastLogIndex\x18\x03 \x01(\x03R\flastLogIndex\x12 \n" +
	"\vlastLogTerm\x18\x04 \x01(\x03R\vlastLogTerm\"a\n" +
	"\x13RequestVoteResponse\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x03R\x04term\x12 \n" +
	"\vvoteGranted\x18\x02 \x01(\bR\vvoteGranted\x12\x14\n" +
	"\x05error\x18\x03 \x01(\tR\x05error\"N\n" +
	"\fStoreRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\x12\x16\n" +
	"\x06bucket\x18\x03 \x01(\tR\x06bucket\"6\n" +
	"\n" +
	"GetRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x16\n" +
	"\x06bucket\x18\x02 \x01(\tR\x06bucket\"9\n" +
	"\rDeleteRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x16\n" +
	"\x06bucket\x18\x02 \x01(\tR\x06bucket\"<\n" +
	"\x13CauseFailureRequest\x12%\n" +
	"\x04type\x18\x01 \x01(\x0e2\x11.orca.FailureTypeR\x04type*3\n" +
	"\aLogType\x12\r\n" +
	"\tOPERATION\x10\x00\x12\v\n" +
	"\aFAILURE\x10\x01\x12\f\n" +
	"\bRECOVERY\x10\x02*>\n" +
	"\vFailureType\x12\n" +
	"\n" +
	"\x06REVIVE\x10\x00\x12\n" +
	"\n" +
	"\x06RANDOM\x10\x01\x12\n" +
	"\n" +
	"\x06LEADER\x10\x02\x12\v\n" +
	"\aREPLICA\x10\x032\x99\x02\n" +
	"\x04Orca\x12H\n" +
	"\rAppendEntries\x12\x1a.orca.AppendEntriesRequest\x1a\x1b.orca.AppendEntriesResponse\x12B\n" +
	"\vRequestVote\x12\x18.orca.RequestVoteRequest\x1a\x19.orca.RequestVoteResponse\x12E\n" +
	"\fCauseFailure\x12\x19.orca.CauseFailureRequest\x1a\x1a.google.protobuf.BoolValue\x12<\n" +
	"\x06Health\x12\x16.google.protobuf.Empty\x1a\x1a.google.protobuf.BoolValueB\tZ\a/orcapbb\x06proto3"

var (
	file_orca_proto_rawDescOnce sync.Once
	file_orca_proto_rawDescData []byte
)

func file_orca_proto_rawDescGZIP() []byte {
	file_orca_proto_rawDescOnce.Do(func() {
		file_orca_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_orca_proto_rawDesc), len(file_orca_proto_rawDesc)))
	})
	return file_orca_proto_rawDescData
}

var file_orca_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_orca_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_orca_proto_goTypes = []any{
	(LogType)(0),                  // 0: orca.LogType
	(FailureType)(0),              // 1: orca.FailureType
	(*LogEntry)(nil),              // 2: orca.LogEntry
	(*AppendEntriesRequest)(nil),  // 3: orca.AppendEntriesRequest
	(*AppendEntriesResponse)(nil), // 4: orca.AppendEntriesResponse
	(*RequestVoteRequest)(nil),    // 5: orca.RequestVoteRequest
	(*RequestVoteResponse)(nil),   // 6: orca.RequestVoteResponse
	(*StoreRequest)(nil),          // 7: orca.StoreRequest
	(*GetRequest)(nil),            // 8: orca.GetRequest
	(*DeleteRequest)(nil),         // 9: orca.DeleteRequest
	(*CauseFailureRequest)(nil),   // 10: orca.CauseFailureRequest
	(*emptypb.Empty)(nil),         // 11: google.protobuf.Empty
	(*wrapperspb.BoolValue)(nil),  // 12: google.protobuf.BoolValue
}
var file_orca_proto_depIdxs = []int32{
	0,  // 0: orca.LogEntry.logType:type_name -> orca.LogType
	2,  // 1: orca.AppendEntriesRequest.entries:type_name -> orca.LogEntry
	1,  // 2: orca.CauseFailureRequest.type:type_name -> orca.FailureType
	3,  // 3: orca.Orca.AppendEntries:input_type -> orca.AppendEntriesRequest
	5,  // 4: orca.Orca.RequestVote:input_type -> orca.RequestVoteRequest
	10, // 5: orca.Orca.CauseFailure:input_type -> orca.CauseFailureRequest
	11, // 6: orca.Orca.Health:input_type -> google.protobuf.Empty
	4,  // 7: orca.Orca.AppendEntries:output_type -> orca.AppendEntriesResponse
	6,  // 8: orca.Orca.RequestVote:output_type -> orca.RequestVoteResponse
	12, // 9: orca.Orca.CauseFailure:output_type -> google.protobuf.BoolValue
	12, // 10: orca.Orca.Health:output_type -> google.protobuf.BoolValue
	7,  // [7:11] is the sub-list for method output_type
	3,  // [3:7] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_orca_proto_init() }
func file_orca_proto_init() {
	if File_orca_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_orca_proto_rawDesc), len(file_orca_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_orca_proto_goTypes,
		DependencyIndexes: file_orca_proto_depIdxs,
		EnumInfos:         file_orca_proto_enumTypes,
		MessageInfos:      file_orca_proto_msgTypes,
	}.Build()
	File_orca_proto = out.File
	file_orca_proto_goTypes = nil
	file_orca_proto_depIdxs = nil
}
