// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: rcppb/rcp.proto

package rcppb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type LogType int32

const (
	LogType_STORE    LogType = 0
	LogType_DELETE   LogType = 1
	LogType_FAILURE  LogType = 2
	LogType_RECOVERY LogType = 3
)

// Enum value maps for LogType.
var (
	LogType_name = map[int32]string{
		0: "STORE",
		1: "DELETE",
		2: "FAILURE",
		3: "RECOVERY",
	}
	LogType_value = map[string]int32{
		"STORE":    0,
		"DELETE":   1,
		"FAILURE":  2,
		"RECOVERY": 3,
	}
)

func (x LogType) Enum() *LogType {
	p := new(LogType)
	*p = x
	return p
}

func (x LogType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (LogType) Descriptor() protoreflect.EnumDescriptor {
	return file_rcppb_rcp_proto_enumTypes[0].Descriptor()
}

func (LogType) Type() protoreflect.EnumType {
	return &file_rcppb_rcp_proto_enumTypes[0]
}

func (x LogType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use LogType.Descriptor instead.
func (LogType) EnumDescriptor() ([]byte, []int) {
	return file_rcppb_rcp_proto_rawDescGZIP(), []int{0}
}

type LogEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LogType       LogType                `protobuf:"varint,1,opt,name=logType,proto3,enum=rcppb.LogType" json:"logType,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=nodeId,proto3" json:"nodeId,omitempty"`
	Key           string                 `protobuf:"bytes,3,opt,name=key,proto3" json:"key,omitempty"`
	Value         string                 `protobuf:"bytes,4,opt,name=value,proto3" json:"value,omitempty"`
	Bucket        string                 `protobuf:"bytes,5,opt,name=bucket,proto3" json:"bucket,omitempty"`
	Term          int64                  `protobuf:"varint,6,opt,name=term,proto3" json:"term,omitempty"` // string callbackChannelId = 8;
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEntry) Reset() {
	*x = LogEntry{}
	mi := &file_rcppb_rcp_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEntry) ProtoMessage() {}

func (x *LogEntry) ProtoReflect() protoreflect.Message {
	mi := &file_rcppb_rcp_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEntry.ProtoReflect.Descriptor instead.
func (*LogEntry) Descriptor() ([]byte, []int) {
	return file_rcppb_rcp_proto_rawDescGZIP(), []int{0}
}

func (x *LogEntry) GetLogType() LogType {
	if x != nil {
		return x.LogType
	}
	return LogType_STORE
}

func (x *LogEntry) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *LogEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *LogEntry) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

func (x *LogEntry) GetBucket() string {
	if x != nil {
		return x.Bucket
	}
	return ""
}

func (x *LogEntry) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

type AppendEntriesReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int64                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	LeaderId      string                 `protobuf:"bytes,2,opt,name=leaderId,proto3" json:"leaderId,omitempty"`
	PrevLogIndex  int64                  `protobuf:"varint,3,opt,name=prevLogIndex,proto3" json:"prevLogIndex,omitempty"`
	PrevLogTerm   int64                  `protobuf:"varint,4,opt,name=prevLogTerm,proto3" json:"prevLogTerm,omitempty"`
	Entries       []*LogEntry            `protobuf:"bytes,5,rep,name=entries,proto3" json:"entries,omitempty"`
	LeaderCommit  int64                  `protobuf:"varint,6,opt,name=leaderCommit,proto3" json:"leaderCommit,omitempty"` // int64 delay = 7;
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendEntriesReq) Reset() {
	*x = AppendEntriesReq{}
	mi := &file_rcppb_rcp_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEntriesReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEntriesReq) ProtoMessage() {}

func (x *AppendEntriesReq) ProtoReflect() protoreflect.Message {
	mi := &file_rcppb_rcp_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEntriesReq.ProtoReflect.Descriptor instead.
func (*AppendEntriesReq) Descriptor() ([]byte, []int) {
	return file_rcppb_rcp_proto_rawDescGZIP(), []int{1}
}

func (x *AppendEntriesReq) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *AppendEntriesReq) GetLeaderId() string {
	if x != nil {
		return x.LeaderId
	}
	return ""
}

func (x *AppendEntriesReq) GetPrevLogIndex() int64 {
	if x != nil {
		return x.PrevLogIndex
	}
	return 0
}

func (x *AppendEntriesReq) GetPrevLogTerm() int64 {
	if x != nil {
		return x.PrevLogTerm
	}
	return 0
}

func (x *AppendEntriesReq) GetEntries() []*LogEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

func (x *AppendEntriesReq) GetLeaderCommit() int64 {
	if x != nil {
		return x.LeaderCommit
	}
	return 0
}

type AppendEntriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int64                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	Success       bool                   `protobuf:"varint,2,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendEntriesResponse) Reset() {
	*x = AppendEntriesResponse{}
	mi := &file_rcppb_rcp_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendEntriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendEntriesResponse) ProtoMessage() {}

func (x *AppendEntriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rcppb_rcp_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendEntriesResponse.ProtoReflect.Descriptor instead.
func (*AppendEntriesResponse) Descriptor() ([]byte, []int) {
	return file_rcppb_rcp_proto_rawDescGZIP(), []int{2}
}

func (x *AppendEntriesResponse) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *AppendEntriesResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RequestVoteReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int64                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	CandidateId   string                 `protobuf:"bytes,2,opt,name=candidateId,proto3" json:"candidateId,omitempty"`
	LastLogIndex  int64                  `protobuf:"varint,3,opt,name=lastLogIndex,proto3" json:"lastLogIndex,omitempty"`
	LastLogTerm   int64                  `protobuf:"varint,4,opt,name=lastLogTerm,proto3" json:"lastLogTerm,omitempty"` // int64 delay = 5;
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestVoteReq) Reset() {
	*x = RequestVoteReq{}
	mi := &file_rcppb_rcp_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestVoteReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVoteReq) ProtoMessage() {}

func (x *RequestVoteReq) ProtoReflect() protoreflect.Message {
	mi := &file_rcppb_rcp_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVoteReq.ProtoReflect.Descriptor instead.
func (*RequestVoteReq) Descriptor() ([]byte, []int) {
	return file_rcppb_rcp_proto_rawDescGZIP(), []int{3}
}

func (x *RequestVoteReq) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RequestVoteReq) GetCandidateId() string {
	if x != nil {
		return x.CandidateId
	}
	return ""
}

func (x *RequestVoteReq) GetLastLogIndex() int64 {
	if x != nil {
		return x.LastLogIndex
	}
	return 0
}

func (x *RequestVoteReq) GetLastLogTerm() int64 {
	if x != nil {
		return x.LastLogTerm
	}
	return 0
}

type RequestVoteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Term          int64                  `protobuf:"varint,1,opt,name=term,proto3" json:"term,omitempty"`
	VoteGranted   bool                   `protobuf:"varint,2,opt,name=voteGranted,proto3" json:"voteGranted,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestVoteResponse) Reset() {
	*x = RequestVoteResponse{}
	mi := &file_rcppb_rcp_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestVoteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestVoteResponse) ProtoMessage() {}

func (x *RequestVoteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rcppb_rcp_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestVoteResponse.ProtoReflect.Descriptor instead.
func (*RequestVoteResponse) Descriptor() ([]byte, []int) {
	return file_rcppb_rcp_proto_rawDescGZIP(), []int{4}
}

func (x *RequestVoteResponse) GetTerm() int64 {
	if x != nil {
		return x.Term
	}
	return 0
}

func (x *RequestVoteResponse) GetVoteGranted() bool {
	if x != nil {
		return x.VoteGranted
	}
	return false
}

type GetValueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetValueResponse) Reset() {
	*x = GetValueResponse{}
	mi := &file_rcppb_rcp_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetValueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetValueResponse) ProtoMessage() {}

func (x *GetValueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_rcppb_rcp_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetValueResponse.ProtoReflect.Descriptor instead.
func (*GetValueResponse) Descriptor() ([]byte, []int) {
	return file_rcppb_rcp_proto_rawDescGZIP(), []int{5}
}

func (x *GetValueResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *GetValueResponse) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type HealthzRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthzRequest) Reset() {
	*x = HealthzRequest{}
	mi := &file_rcppb_rcp_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthzRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthzRequest) ProtoMessage() {}

func (x *HealthzRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rcppb_rcp_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthzRequest.ProtoReflect.Descriptor instead.
func (*HealthzRequest) Descriptor() ([]byte, []int) {
	return file_rcppb_rcp_proto_rawDescGZIP(), []int{6}
}

type CauseFailureRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          string                 `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CauseFailureRequest) Reset() {
	*x = CauseFailureRequest{}
	mi := &file_rcppb_rcp_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CauseFailureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CauseFailureRequest) ProtoMessage() {}

func (x *CauseFailureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_rcppb_rcp_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CauseFailureRequest.ProtoReflect.Descriptor instead.
func (*CauseFailureRequest) Descriptor() ([]byte, []int) {
	return file_rcppb_rcp_proto_rawDescGZIP(), []int{7}
}

func (x *CauseFailureRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

var File_rcppb_rcp_proto protoreflect.FileDescriptor

const file_rcppb_rcp_proto_rawDesc = "" +
	"\n" +
	"\x0frcppb/rcp.proto\x12\x05rcppb\x1a\x1egoogle/protobuf/wrappers.proto\"\xa0\x01\n" +
	"\bLogEntry\x12(\n" +
	"\alogType\x18\x01 \x01(\x0e2\x0e.rcppb.LogTypeR\alogType\x12\x16\n" +
	"\x06nodeId\x18\x02 \x01(\tR\x06nodeId\x12\x10\n" +
	"\x03key\x18\x03 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x04 \x01(\tR\x05value\x12\x16\n" +
	"\x06bucket\x18\x05 \x01(\tR\x06bucket\x12\x12\n" +
	"\x04term\x18\x06 \x01(\x03R\x04term\"\xd7\x01\n" +
	"\x10AppendEntriesReq\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x03R\x04term\x12\x1a\n" +
	"\bleaderId\x18\x02 \x01(\tR\bleaderId\x12\"\n" +
	"\fprevLogIndex\x18\x03 \x01(\x03R\fprevLogIndex\x12 \n" +
	"\vprevLogTerm\x18\x04 \x01(\x03R\vprevLogTerm\x12)\n" +
	"\aentries\x18\x05 \x03(\v2\x0f.rcppb.LogEntryR\aentries\x12\"\n" +
	"\fleaderCommit\x18\x06 \x01(\x03R\fleaderCommit\"E\n" +
	"\x15AppendEntriesResponse\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x03R\x04term\x12\x18\n" +
	"\asuccess\x18\x02 \x01(\bR\asuccess\"\x8c\x01\n" +
	"\x0eRequestVoteReq\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x03R\x04term\x12 \n" +
	"\vcandidateId\x18\x02 \x01(\tR\vcandidateId\x12\"\n" +
	"\flastLogIndex\x18\x03 \x01(\x03R\flastLogIndex\x12 \n" +
	"\vlastLogTerm\x18\x04 \x01(\x03R\vlastLogTerm\"K\n" +
	"\x13RequestVoteResponse\x12\x12\n" +
	"\x04term\x18\x01 \x01(\x03R\x04term\x12 \n" +
	"\vvoteGranted\x18\x02 \x01(\bR\vvoteGranted\"B\n" +
	"\x10GetValueResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\x10\n" +
	"\x0eHealthzRequest\")\n" +
	"\x13CauseFailureRequest\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type*;\n" +
	"\aLogType\x12\t\n" +
	"\x05STORE\x10\x00\x12\n" +
	"\n" +
	"\x06DELETE\x10\x01\x12\v\n" +
	"\aFAILURE\x10\x02\x12\f\n" +
	"\bRECOVERY\x10\x032\xe4\x02\n" +
	"\x03RCP\x12H\n" +
	"\rAppendEntries\x12\x17.rcppb.AppendEntriesReq\x1a\x1c.rcppb.AppendEntriesResponse\"\x00\x12B\n" +
	"\vRequestVote\x12\x15.rcppb.RequestVoteReq\x1a\x1a.rcppb.RequestVoteResponse\"\x00\x12E\n" +
	"\tSetStatus\x12\x1a.google.protobuf.BoolValue\x1a\x1a.google.protobuf.BoolValue\"\x00\x12>\n" +
	"\aHealthz\x12\x15.rcppb.HealthzRequest\x1a\x1a.google.protobuf.BoolValue\"\x00\x12H\n" +
	"\fCauseFailure\x12\x1a.rcppb.CauseFailureRequest\x1a\x1a.google.protobuf.BoolValue\"\x00B\bZ\x06/rcppbb\x06proto3"

var (
	file_rcppb_rcp_proto_rawDescOnce sync.Once
	file_rcppb_rcp_proto_rawDescData []byte
)

func file_rcppb_rcp_proto_rawDescGZIP() []byte {
	file_rcppb_rcp_proto_rawDescOnce.Do(func() {
		file_rcppb_rcp_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_rcppb_rcp_proto_rawDesc), len(file_rcppb_rcp_proto_rawDesc)))
	})
	return file_rcppb_rcp_proto_rawDescData
}

var file_rcppb_rcp_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_rcppb_rcp_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_rcppb_rcp_proto_goTypes = []any{
	(LogType)(0),                  // 0: rcppb.LogType
	(*LogEntry)(nil),              // 1: rcppb.LogEntry
	(*AppendEntriesReq)(nil),      // 2: rcppb.AppendEntriesReq
	(*AppendEntriesResponse)(nil), // 3: rcppb.AppendEntriesResponse
	(*RequestVoteReq)(nil),        // 4: rcppb.RequestVoteReq
	(*RequestVoteResponse)(nil),   // 5: rcppb.RequestVoteResponse
	(*GetValueResponse)(nil),      // 6: rcppb.GetValueResponse
	(*HealthzRequest)(nil),        // 7: rcppb.HealthzRequest
	(*CauseFailureRequest)(nil),   // 8: rcppb.CauseFailureRequest
	(*wrapperspb.BoolValue)(nil),  // 9: google.protobuf.BoolValue
}
var file_rcppb_rcp_proto_depIdxs = []int32{
	0, // 0: rcppb.LogEntry.logType:type_name -> rcppb.LogType
	1, // 1: rcppb.AppendEntriesReq.entries:type_name -> rcppb.LogEntry
	2, // 2: rcppb.RCP.AppendEntries:input_type -> rcppb.AppendEntriesReq
	4, // 3: rcppb.RCP.RequestVote:input_type -> rcppb.RequestVoteReq
	9, // 4: rcppb.RCP.SetStatus:input_type -> google.protobuf.BoolValue
	7, // 5: rcppb.RCP.Healthz:input_type -> rcppb.HealthzRequest
	8, // 6: rcppb.RCP.CauseFailure:input_type -> rcppb.CauseFailureRequest
	3, // 7: rcppb.RCP.AppendEntries:output_type -> rcppb.AppendEntriesResponse
	5, // 8: rcppb.RCP.RequestVote:output_type -> rcppb.RequestVoteResponse
	9, // 9: rcppb.RCP.SetStatus:output_type -> google.protobuf.BoolValue
	9, // 10: rcppb.RCP.Healthz:output_type -> google.protobuf.BoolValue
	9, // 11: rcppb.RCP.CauseFailure:output_type -> google.protobuf.BoolValue
	7, // [7:12] is the sub-list for method output_type
	2, // [2:7] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_rcppb_rcp_proto_init() }
func file_rcppb_rcp_proto_init() {
	if File_rcppb_rcp_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_rcppb_rcp_proto_rawDesc), len(file_rcppb_rcp_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_rcppb_rcp_proto_goTypes,
		DependencyIndexes: file_rcppb_rcp_proto_depIdxs,
		EnumInfos:         file_rcppb_rcp_proto_enumTypes,
		MessageInfos:      file_rcppb_rcp_proto_msgTypes,
	}.Build()
	File_rcppb_rcp_proto = out.File
	file_rcppb_rcp_proto_goTypes = nil
	file_rcppb_rcp_proto_depIdxs = nil
}
