// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.29.3
// source: rcppb/rcp.proto

package rcppb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	wrapperspb "google.golang.org/protobuf/types/known/wrapperspb"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	RCP_AppendEntries_FullMethodName = "/rcppb.RCP/AppendEntries"
	RCP_RequestVote_FullMethodName   = "/rcppb.RCP/RequestVote"
	RCP_Store_FullMethodName         = "/rcppb.RCP/Store"
	RCP_Get_FullMethodName           = "/rcppb.RCP/Get"
	RCP_SetStatus_FullMethodName     = "/rcppb.RCP/SetStatus"
)

// RCPClient is the client API for RCP service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type RCPClient interface {
	AppendEntries(ctx context.Context, in *AppendEntriesReq, opts ...grpc.CallOption) (*AppendEntriesResponse, error)
	RequestVote(ctx context.Context, in *RequestVoteReq, opts ...grpc.CallOption) (*RequestVoteResponse, error)
	Store(ctx context.Context, in *KV, opts ...grpc.CallOption) (*StoreKVResponse, error)
	Get(ctx context.Context, in *GetValueReq, opts ...grpc.CallOption) (*GetValueResponse, error)
	SetStatus(ctx context.Context, in *wrapperspb.BoolValue, opts ...grpc.CallOption) (*wrapperspb.BoolValue, error)
}

type rCPClient struct {
	cc grpc.ClientConnInterface
}

func NewRCPClient(cc grpc.ClientConnInterface) RCPClient {
	return &rCPClient{cc}
}

func (c *rCPClient) AppendEntries(ctx context.Context, in *AppendEntriesReq, opts ...grpc.CallOption) (*AppendEntriesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AppendEntriesResponse)
	err := c.cc.Invoke(ctx, RCP_AppendEntries_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rCPClient) RequestVote(ctx context.Context, in *RequestVoteReq, opts ...grpc.CallOption) (*RequestVoteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RequestVoteResponse)
	err := c.cc.Invoke(ctx, RCP_RequestVote_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rCPClient) Store(ctx context.Context, in *KV, opts ...grpc.CallOption) (*StoreKVResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StoreKVResponse)
	err := c.cc.Invoke(ctx, RCP_Store_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rCPClient) Get(ctx context.Context, in *GetValueReq, opts ...grpc.CallOption) (*GetValueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetValueResponse)
	err := c.cc.Invoke(ctx, RCP_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *rCPClient) SetStatus(ctx context.Context, in *wrapperspb.BoolValue, opts ...grpc.CallOption) (*wrapperspb.BoolValue, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(wrapperspb.BoolValue)
	err := c.cc.Invoke(ctx, RCP_SetStatus_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// RCPServer is the server API for RCP service.
// All implementations must embed UnimplementedRCPServer
// for forward compatibility.
type RCPServer interface {
	AppendEntries(context.Context, *AppendEntriesReq) (*AppendEntriesResponse, error)
	RequestVote(context.Context, *RequestVoteReq) (*RequestVoteResponse, error)
	Store(context.Context, *KV) (*StoreKVResponse, error)
	Get(context.Context, *GetValueReq) (*GetValueResponse, error)
	SetStatus(context.Context, *wrapperspb.BoolValue) (*wrapperspb.BoolValue, error)
	mustEmbedUnimplementedRCPServer()
}

// UnimplementedRCPServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedRCPServer struct{}

func (UnimplementedRCPServer) AppendEntries(context.Context, *AppendEntriesReq) (*AppendEntriesResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AppendEntries not implemented")
}
func (UnimplementedRCPServer) RequestVote(context.Context, *RequestVoteReq) (*RequestVoteResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RequestVote not implemented")
}
func (UnimplementedRCPServer) Store(context.Context, *KV) (*StoreKVResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Store not implemented")
}
func (UnimplementedRCPServer) Get(context.Context, *GetValueReq) (*GetValueResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedRCPServer) SetStatus(context.Context, *wrapperspb.BoolValue) (*wrapperspb.BoolValue, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetStatus not implemented")
}
func (UnimplementedRCPServer) mustEmbedUnimplementedRCPServer() {}
func (UnimplementedRCPServer) testEmbeddedByValue()             {}

// UnsafeRCPServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to RCPServer will
// result in compilation errors.
type UnsafeRCPServer interface {
	mustEmbedUnimplementedRCPServer()
}

func RegisterRCPServer(s grpc.ServiceRegistrar, srv RCPServer) {
	// If the following call pancis, it indicates UnimplementedRCPServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&RCP_ServiceDesc, srv)
}

func _RCP_AppendEntries_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AppendEntriesReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RCPServer).AppendEntries(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RCP_AppendEntries_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RCPServer).AppendEntries(ctx, req.(*AppendEntriesReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RCP_RequestVote_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestVoteReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RCPServer).RequestVote(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RCP_RequestVote_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RCPServer).RequestVote(ctx, req.(*RequestVoteReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RCP_Store_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(KV)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RCPServer).Store(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RCP_Store_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RCPServer).Store(ctx, req.(*KV))
	}
	return interceptor(ctx, in, info, handler)
}

func _RCP_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetValueReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RCPServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RCP_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RCPServer).Get(ctx, req.(*GetValueReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _RCP_SetStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(wrapperspb.BoolValue)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(RCPServer).SetStatus(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: RCP_SetStatus_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(RCPServer).SetStatus(ctx, req.(*wrapperspb.BoolValue))
	}
	return interceptor(ctx, in, info, handler)
}

// RCP_ServiceDesc is the grpc.ServiceDesc for RCP service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var RCP_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "rcppb.RCP",
	HandlerType: (*RCPServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AppendEntries",
			Handler:    _RCP_AppendEntries_Handler,
		},
		{
			MethodName: "RequestVote",
			Handler:    _RCP_RequestVote_Handler,
		},
		{
			MethodName: "Store",
			Handler:    _RCP_Store_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _RCP_Get_Handler,
		},
		{
			MethodName: "SetStatus",
			Handler:    _RCP_SetStatus_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "rcppb/rcp.proto",
}
